--------------------------------------------------------
--  File created - pondělí-listopadu-25-2019   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence HIBERNATE_SEQUENCE
--------------------------------------------------------

   CREATE SEQUENCE  "SKIPPER"."HIBERNATE_SEQUENCE"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ACTION
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."ACTION" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"SPEL" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DEFERRED_EVENTS
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."DEFERRED_EVENTS" 
   (	"JPA_REPOSITORY_STATE_ID" NUMBER(19,0), 
	"DEFERRED_EVENTS" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table flyway_schema_history
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."flyway_schema_history" 
   (	"installed_rank" NUMBER(*,0), 
	"version" VARCHAR2(50 BYTE), 
	"description" VARCHAR2(200 BYTE), 
	"type" VARCHAR2(20 BYTE), 
	"script" VARCHAR2(1000 BYTE), 
	"checksum" NUMBER(*,0), 
	"installed_by" VARCHAR2(100 BYTE), 
	"installed_on" TIMESTAMP (6) DEFAULT CURRENT_TIMESTAMP, 
	"execution_time" NUMBER(*,0), 
	"success" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table GUARD
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."GUARD" 
   (	"ID" NUMBER(19,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"SPEL" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SKIPPER_APP_DEPLOYER_DATA
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."SKIPPER_APP_DEPLOYER_DATA" 
   (	"ID" NUMBER(19,0), 
	"OBJECT_VERSION" NUMBER(19,0), 
	"DEPLOYMENT_DATA" CLOB, 
	"RELEASE_NAME" VARCHAR2(255 CHAR), 
	"RELEASE_VERSION" NUMBER(10,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("DEPLOYMENT_DATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table SKIPPER_INFO
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."SKIPPER_INFO" 
   (	"ID" NUMBER(19,0), 
	"OBJECT_VERSION" NUMBER(19,0), 
	"DELETED" TIMESTAMP (6), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"FIRST_DEPLOYED" TIMESTAMP (6), 
	"LAST_DEPLOYED" TIMESTAMP (6), 
	"STATUS_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SKIPPER_MANIFEST
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."SKIPPER_MANIFEST" 
   (	"ID" NUMBER(19,0), 
	"OBJECT_VERSION" NUMBER(19,0), 
	"DATA" CLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("DATA") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table SKIPPER_PACKAGE_FILE
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."SKIPPER_PACKAGE_FILE" 
   (	"ID" NUMBER(19,0), 
	"PACKAGE_BYTES" BLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("PACKAGE_BYTES") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table SKIPPER_PACKAGE_METADATA
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."SKIPPER_PACKAGE_METADATA" 
   (	"ID" NUMBER(19,0), 
	"OBJECT_VERSION" NUMBER(19,0), 
	"API_VERSION" VARCHAR2(255 CHAR), 
	"DESCRIPTION" CLOB, 
	"DISPLAY_NAME" VARCHAR2(255 CHAR), 
	"ICON_URL" CLOB, 
	"KIND" VARCHAR2(255 CHAR), 
	"MAINTAINER" VARCHAR2(255 CHAR), 
	"NAME" VARCHAR2(255 CHAR), 
	"ORIGIN" VARCHAR2(255 CHAR), 
	"PACKAGE_HOME_URL" CLOB, 
	"PACKAGE_SOURCE_URL" CLOB, 
	"REPOSITORY_ID" NUMBER(19,0), 
	"REPOSITORY_NAME" VARCHAR2(255 CHAR), 
	"SHA256" VARCHAR2(255 CHAR), 
	"TAGS" CLOB, 
	"VERSION" VARCHAR2(255 CHAR), 
	"PACKAGEFILE_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("DESCRIPTION") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("ICON_URL") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("PACKAGE_HOME_URL") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("PACKAGE_SOURCE_URL") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("TAGS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table SKIPPER_RELEASE
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."SKIPPER_RELEASE" 
   (	"ID" NUMBER(19,0), 
	"OBJECT_VERSION" NUMBER(19,0), 
	"CONFIG_VALUES_STRING" CLOB, 
	"NAME" VARCHAR2(255 CHAR), 
	"PACKAGE_METADATA_ID" NUMBER(19,0), 
	"PKG_JSON_STRING" CLOB, 
	"PLATFORM_NAME" VARCHAR2(255 CHAR), 
	"REPOSITORY_ID" NUMBER(19,0), 
	"VERSION" NUMBER(10,0), 
	"INFO_ID" NUMBER(19,0), 
	"MANIFEST_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("CONFIG_VALUES_STRING") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) 
 LOB ("PKG_JSON_STRING") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table SKIPPER_REPOSITORY
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."SKIPPER_REPOSITORY" 
   (	"ID" NUMBER(19,0), 
	"OBJECT_VERSION" NUMBER(19,0), 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"LOCAL" NUMBER(1,0), 
	"NAME" VARCHAR2(255 CHAR), 
	"REPO_ORDER" NUMBER(10,0), 
	"SOURCE_URL" CLOB, 
	"URL" CLOB
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("SOURCE_URL") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) 
 LOB ("URL") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 106496 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table SKIPPER_STATUS
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."SKIPPER_STATUS" 
   (	"ID" NUMBER(19,0), 
	"PLATFORM_STATUS" CLOB, 
	"STATUS_CODE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("PLATFORM_STATUS") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table STATE
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."STATE" 
   (	"ID" NUMBER(19,0), 
	"INITIAL_STATE" NUMBER(1,0), 
	"KIND" NUMBER(10,0), 
	"MACHINE_ID" VARCHAR2(255 CHAR), 
	"REGION" VARCHAR2(255 CHAR), 
	"STATE" VARCHAR2(255 CHAR), 
	"SUBMACHINE_ID" VARCHAR2(255 CHAR), 
	"INITIAL_ACTION_ID" NUMBER(19,0), 
	"PARENT_STATE_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATE_ENTRY_ACTIONS
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."STATE_ENTRY_ACTIONS" 
   (	"JPA_REPOSITORY_STATE_ID" NUMBER(19,0), 
	"ENTRY_ACTIONS_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATE_EXIT_ACTIONS
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."STATE_EXIT_ACTIONS" 
   (	"JPA_REPOSITORY_STATE_ID" NUMBER(19,0), 
	"EXIT_ACTIONS_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STATE_MACHINE
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."STATE_MACHINE" 
   (	"MACHINE_ID" VARCHAR2(255 CHAR), 
	"STATE" VARCHAR2(255 CHAR), 
	"STATE_MACHINE_CONTEXT" BLOB
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("STATE_MACHINE_CONTEXT") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
--------------------------------------------------------
--  DDL for Table STATE_STATE_ACTIONS
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."STATE_STATE_ACTIONS" 
   (	"JPA_REPOSITORY_STATE_ID" NUMBER(19,0), 
	"STATE_ACTIONS_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSITION
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."TRANSITION" 
   (	"ID" NUMBER(19,0), 
	"EVENT" VARCHAR2(255 CHAR), 
	"KIND" NUMBER(10,0), 
	"MACHINE_ID" VARCHAR2(255 CHAR), 
	"GUARD_ID" NUMBER(19,0), 
	"SOURCE_ID" NUMBER(19,0), 
	"TARGET_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSITION_ACTIONS
--------------------------------------------------------

  CREATE TABLE "SKIPPER"."TRANSITION_ACTIONS" 
   (	"JPA_REPOSITORY_TRANSITION_ID" NUMBER(19,0), 
	"ACTIONS_ID" NUMBER(19,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
REM INSERTING into SKIPPER.ACTION
SET DEFINE OFF;
REM INSERTING into SKIPPER.DEFERRED_EVENTS
SET DEFINE OFF;
REM INSERTING into SKIPPER."flyway_schema_history"
SET DEFINE OFF;
Insert into SKIPPER."flyway_schema_history" ("installed_rank","version","description","type","script","checksum","installed_by","installed_on","execution_time","success") values ('1','1','Initial Setup','JDBC','org.springframework.cloud.skipper.server.db.migration.oracle.V1__Initial_Setup',null,'SKIPPER',to_timestamp('25.11.19 19:51:24,777000000','DD.MM.RR HH24:MI:SSXFF'),'647','1');
Insert into SKIPPER."flyway_schema_history" ("installed_rank","version","description","type","script","checksum","installed_by","installed_on","execution_time","success") values ('2',null,'Hibernate Sequence','JDBC','org.springframework.cloud.skipper.server.db.migration.oracle.R__Hibernate_Sequence',null,'SKIPPER',to_timestamp('25.11.19 19:51:24,809000000','DD.MM.RR HH24:MI:SSXFF'),'10','1');
REM INSERTING into SKIPPER.GUARD
SET DEFINE OFF;
REM INSERTING into SKIPPER.SKIPPER_APP_DEPLOYER_DATA
SET DEFINE OFF;
REM INSERTING into SKIPPER.SKIPPER_INFO
SET DEFINE OFF;
REM INSERTING into SKIPPER.SKIPPER_MANIFEST
SET DEFINE OFF;
REM INSERTING into SKIPPER.SKIPPER_PACKAGE_FILE
SET DEFINE OFF;
REM INSERTING into SKIPPER.SKIPPER_PACKAGE_METADATA
SET DEFINE OFF;
REM INSERTING into SKIPPER.SKIPPER_RELEASE
SET DEFINE OFF;
REM INSERTING into SKIPPER.SKIPPER_REPOSITORY
SET DEFINE OFF;
Insert into SKIPPER.SKIPPER_REPOSITORY (ID,OBJECT_VERSION,DESCRIPTION,LOCAL,NAME,REPO_ORDER) values ('1','0','Default local database backed repository','1','local','1');
REM INSERTING into SKIPPER.SKIPPER_STATUS
SET DEFINE OFF;
REM INSERTING into SKIPPER.STATE
SET DEFINE OFF;
REM INSERTING into SKIPPER.STATE_ENTRY_ACTIONS
SET DEFINE OFF;
REM INSERTING into SKIPPER.STATE_EXIT_ACTIONS
SET DEFINE OFF;
REM INSERTING into SKIPPER.STATE_MACHINE
SET DEFINE OFF;
REM INSERTING into SKIPPER.STATE_STATE_ACTIONS
SET DEFINE OFF;
REM INSERTING into SKIPPER.TRANSITION
SET DEFINE OFF;
REM INSERTING into SKIPPER.TRANSITION_ACTIONS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index flyway_schema_history_pk
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."flyway_schema_history_pk" ON "SKIPPER"."flyway_schema_history" ("installed_rank") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index flyway_schema_history_s_idx
--------------------------------------------------------

  CREATE INDEX "SKIPPER"."flyway_schema_history_s_idx" ON "SKIPPER"."flyway_schema_history" ("success") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_PKG_NAME
--------------------------------------------------------

  CREATE INDEX "SKIPPER"."IDX_PKG_NAME" ON "SKIPPER"."SKIPPER_PACKAGE_METADATA" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_REL_NAME
--------------------------------------------------------

  CREATE INDEX "SKIPPER"."IDX_REL_NAME" ON "SKIPPER"."SKIPPER_RELEASE" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDX_REPO_NAME
--------------------------------------------------------

  CREATE INDEX "SKIPPER"."IDX_REPO_NAME" ON "SKIPPER"."SKIPPER_REPOSITORY" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007355
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007355" ON "SKIPPER"."SKIPPER_APP_DEPLOYER_DATA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007357
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007357" ON "SKIPPER"."SKIPPER_INFO" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007359
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007359" ON "SKIPPER"."SKIPPER_MANIFEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007361
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007361" ON "SKIPPER"."SKIPPER_PACKAGE_FILE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007363
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007363" ON "SKIPPER"."SKIPPER_PACKAGE_METADATA" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007366
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007366" ON "SKIPPER"."SKIPPER_RELEASE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007368
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007368" ON "SKIPPER"."SKIPPER_REPOSITORY" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007370
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007370" ON "SKIPPER"."SKIPPER_STATUS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007372
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007372" ON "SKIPPER"."ACTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007375
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007375" ON "SKIPPER"."GUARD" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007378
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007378" ON "SKIPPER"."STATE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007381
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007381" ON "SKIPPER"."STATE_ENTRY_ACTIONS" ("JPA_REPOSITORY_STATE_ID", "ENTRY_ACTIONS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007384
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007384" ON "SKIPPER"."STATE_EXIT_ACTIONS" ("JPA_REPOSITORY_STATE_ID", "EXIT_ACTIONS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007387
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007387" ON "SKIPPER"."STATE_STATE_ACTIONS" ("JPA_REPOSITORY_STATE_ID", "STATE_ACTIONS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007389
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007389" ON "SKIPPER"."STATE_MACHINE" ("MACHINE_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007391
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007391" ON "SKIPPER"."TRANSITION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_C007394
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_C007394" ON "SKIPPER"."TRANSITION_ACTIONS" ("JPA_REPOSITORY_TRANSITION_ID", "ACTIONS_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073393C00003$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_IL0000073393C00003$$" ON "SKIPPER"."SKIPPER_APP_DEPLOYER_DATA" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073399C00003$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_IL0000073399C00003$$" ON "SKIPPER"."SKIPPER_MANIFEST" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073403C00002$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_IL0000073403C00002$$" ON "SKIPPER"."SKIPPER_PACKAGE_FILE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073407C00004$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_IL0000073407C00004$$" ON "SKIPPER"."SKIPPER_PACKAGE_METADATA" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073407C00006$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_IL0000073407C00006$$" ON "SKIPPER"."SKIPPER_PACKAGE_METADATA" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073407C00011$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_IL0000073407C00011$$" ON "SKIPPER"."SKIPPER_PACKAGE_METADATA" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073407C00012$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_IL0000073407C00012$$" ON "SKIPPER"."SKIPPER_PACKAGE_METADATA" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073407C00016$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_IL0000073407C00016$$" ON "SKIPPER"."SKIPPER_PACKAGE_METADATA" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073419C00003$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_IL0000073419C00003$$" ON "SKIPPER"."SKIPPER_RELEASE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073419C00006$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_IL0000073419C00006$$" ON "SKIPPER"."SKIPPER_RELEASE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073425C00007$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_IL0000073425C00007$$" ON "SKIPPER"."SKIPPER_REPOSITORY" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073425C00008$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_IL0000073425C00008$$" ON "SKIPPER"."SKIPPER_REPOSITORY" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073431C00002$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_IL0000073431C00002$$" ON "SKIPPER"."SKIPPER_STATUS" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  DDL for Index SYS_IL0000073451C00003$$
--------------------------------------------------------

  CREATE UNIQUE INDEX "SKIPPER"."SYS_IL0000073451C00003$$" ON "SKIPPER"."STATE_MACHINE" (
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE( INITIAL 65536 NEXT 1048576 MAXEXTENTS 2147483645
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
  PARALLEL (DEGREE 0 INSTANCES 0) ;
--------------------------------------------------------
--  Constraints for Table ACTION
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."ACTION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."ACTION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table DEFERRED_EVENTS
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."DEFERRED_EVENTS" MODIFY ("JPA_REPOSITORY_STATE_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table flyway_schema_history
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."flyway_schema_history" MODIFY ("installed_rank" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."flyway_schema_history" MODIFY ("description" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."flyway_schema_history" MODIFY ("type" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."flyway_schema_history" MODIFY ("script" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."flyway_schema_history" MODIFY ("installed_by" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."flyway_schema_history" MODIFY ("installed_on" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."flyway_schema_history" MODIFY ("execution_time" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."flyway_schema_history" MODIFY ("success" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."flyway_schema_history" ADD CONSTRAINT "flyway_schema_history_pk" PRIMARY KEY ("installed_rank")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table GUARD
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."GUARD" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."GUARD" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKIPPER_APP_DEPLOYER_DATA
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."SKIPPER_APP_DEPLOYER_DATA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."SKIPPER_APP_DEPLOYER_DATA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKIPPER_INFO
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."SKIPPER_INFO" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."SKIPPER_INFO" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKIPPER_MANIFEST
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."SKIPPER_MANIFEST" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."SKIPPER_MANIFEST" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKIPPER_PACKAGE_FILE
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."SKIPPER_PACKAGE_FILE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."SKIPPER_PACKAGE_FILE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKIPPER_PACKAGE_METADATA
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."SKIPPER_PACKAGE_METADATA" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."SKIPPER_PACKAGE_METADATA" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKIPPER_RELEASE
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."SKIPPER_RELEASE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."SKIPPER_RELEASE" MODIFY ("VERSION" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."SKIPPER_RELEASE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKIPPER_REPOSITORY
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."SKIPPER_REPOSITORY" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."SKIPPER_REPOSITORY" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SKIPPER"."SKIPPER_REPOSITORY" ADD CONSTRAINT "UK_REPOSITORY" UNIQUE ("NAME")
  USING INDEX (CREATE INDEX "SKIPPER"."IDX_REPO_NAME" ON "SKIPPER"."SKIPPER_REPOSITORY" ("NAME") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" )  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKIPPER_STATUS
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."SKIPPER_STATUS" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."SKIPPER_STATUS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATE
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."STATE" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."STATE" MODIFY ("INITIAL_STATE" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."STATE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATE_ENTRY_ACTIONS
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."STATE_ENTRY_ACTIONS" MODIFY ("JPA_REPOSITORY_STATE_ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."STATE_ENTRY_ACTIONS" MODIFY ("ENTRY_ACTIONS_ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."STATE_ENTRY_ACTIONS" ADD PRIMARY KEY ("JPA_REPOSITORY_STATE_ID", "ENTRY_ACTIONS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATE_EXIT_ACTIONS
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."STATE_EXIT_ACTIONS" MODIFY ("JPA_REPOSITORY_STATE_ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."STATE_EXIT_ACTIONS" MODIFY ("EXIT_ACTIONS_ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."STATE_EXIT_ACTIONS" ADD PRIMARY KEY ("JPA_REPOSITORY_STATE_ID", "EXIT_ACTIONS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATE_MACHINE
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."STATE_MACHINE" MODIFY ("MACHINE_ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."STATE_MACHINE" ADD PRIMARY KEY ("MACHINE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table STATE_STATE_ACTIONS
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."STATE_STATE_ACTIONS" MODIFY ("JPA_REPOSITORY_STATE_ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."STATE_STATE_ACTIONS" MODIFY ("STATE_ACTIONS_ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."STATE_STATE_ACTIONS" ADD PRIMARY KEY ("JPA_REPOSITORY_STATE_ID", "STATE_ACTIONS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSITION
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."TRANSITION" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."TRANSITION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSITION_ACTIONS
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."TRANSITION_ACTIONS" MODIFY ("JPA_REPOSITORY_TRANSITION_ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."TRANSITION_ACTIONS" MODIFY ("ACTIONS_ID" NOT NULL ENABLE);
  ALTER TABLE "SKIPPER"."TRANSITION_ACTIONS" ADD PRIMARY KEY ("JPA_REPOSITORY_TRANSITION_ID", "ACTIONS_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table DEFERRED_EVENTS
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."DEFERRED_EVENTS" ADD CONSTRAINT "FK_STATE_DEFERRED_EVENTS" FOREIGN KEY ("JPA_REPOSITORY_STATE_ID")
	  REFERENCES "SKIPPER"."STATE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SKIPPER_INFO
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."SKIPPER_INFO" ADD CONSTRAINT "FK_INFO_STATUS" FOREIGN KEY ("STATUS_ID")
	  REFERENCES "SKIPPER"."SKIPPER_STATUS" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SKIPPER_PACKAGE_METADATA
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."SKIPPER_PACKAGE_METADATA" ADD CONSTRAINT "FK_PACKAGE_METADATA_PFILE" FOREIGN KEY ("PACKAGEFILE_ID")
	  REFERENCES "SKIPPER"."SKIPPER_PACKAGE_FILE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SKIPPER_RELEASE
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."SKIPPER_RELEASE" ADD CONSTRAINT "FK_RELEASE_INFO" FOREIGN KEY ("INFO_ID")
	  REFERENCES "SKIPPER"."SKIPPER_INFO" ("ID") ENABLE;
  ALTER TABLE "SKIPPER"."SKIPPER_RELEASE" ADD CONSTRAINT "FK_RELEASE_MANIFEST" FOREIGN KEY ("MANIFEST_ID")
	  REFERENCES "SKIPPER"."SKIPPER_MANIFEST" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATE
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."STATE" ADD CONSTRAINT "FK_STATE_INITIAL_ACTION" FOREIGN KEY ("INITIAL_ACTION_ID")
	  REFERENCES "SKIPPER"."ACTION" ("ID") ENABLE;
  ALTER TABLE "SKIPPER"."STATE" ADD CONSTRAINT "FK_STATE_PARENT_STATE" FOREIGN KEY ("PARENT_STATE_ID")
	  REFERENCES "SKIPPER"."STATE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATE_ENTRY_ACTIONS
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."STATE_ENTRY_ACTIONS" ADD CONSTRAINT "FK_STATE_ENTRY_ACTIONS_A" FOREIGN KEY ("ENTRY_ACTIONS_ID")
	  REFERENCES "SKIPPER"."ACTION" ("ID") ENABLE;
  ALTER TABLE "SKIPPER"."STATE_ENTRY_ACTIONS" ADD CONSTRAINT "FK_STATE_ENTRY_ACTIONS_S" FOREIGN KEY ("JPA_REPOSITORY_STATE_ID")
	  REFERENCES "SKIPPER"."STATE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATE_EXIT_ACTIONS
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."STATE_EXIT_ACTIONS" ADD CONSTRAINT "FK_STATE_EXIT_ACTIONS_A" FOREIGN KEY ("EXIT_ACTIONS_ID")
	  REFERENCES "SKIPPER"."ACTION" ("ID") ENABLE;
  ALTER TABLE "SKIPPER"."STATE_EXIT_ACTIONS" ADD CONSTRAINT "FK_STATE_EXIT_ACTIONS_S" FOREIGN KEY ("JPA_REPOSITORY_STATE_ID")
	  REFERENCES "SKIPPER"."STATE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table STATE_STATE_ACTIONS
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."STATE_STATE_ACTIONS" ADD CONSTRAINT "FK_STATE_STATE_ACTIONS_A" FOREIGN KEY ("STATE_ACTIONS_ID")
	  REFERENCES "SKIPPER"."ACTION" ("ID") ENABLE;
  ALTER TABLE "SKIPPER"."STATE_STATE_ACTIONS" ADD CONSTRAINT "FK_STATE_STATE_ACTIONS_S" FOREIGN KEY ("JPA_REPOSITORY_STATE_ID")
	  REFERENCES "SKIPPER"."STATE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSITION
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."TRANSITION" ADD CONSTRAINT "FK_TRANSITION_GUARD" FOREIGN KEY ("GUARD_ID")
	  REFERENCES "SKIPPER"."GUARD" ("ID") ENABLE;
  ALTER TABLE "SKIPPER"."TRANSITION" ADD CONSTRAINT "FK_TRANSITION_SOURCE" FOREIGN KEY ("SOURCE_ID")
	  REFERENCES "SKIPPER"."STATE" ("ID") ENABLE;
  ALTER TABLE "SKIPPER"."TRANSITION" ADD CONSTRAINT "FK_TRANSITION_TARGET" FOREIGN KEY ("TARGET_ID")
	  REFERENCES "SKIPPER"."STATE" ("ID") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSITION_ACTIONS
--------------------------------------------------------

  ALTER TABLE "SKIPPER"."TRANSITION_ACTIONS" ADD CONSTRAINT "FK_TRANSITION_ACTIONS_A" FOREIGN KEY ("ACTIONS_ID")
	  REFERENCES "SKIPPER"."ACTION" ("ID") ENABLE;
  ALTER TABLE "SKIPPER"."TRANSITION_ACTIONS" ADD CONSTRAINT "FK_TRANSITION_ACTIONS_T" FOREIGN KEY ("JPA_REPOSITORY_TRANSITION_ID")
	  REFERENCES "SKIPPER"."TRANSITION" ("ID") ENABLE;
